[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$SessionRoot,[string]$EvidenceDirectory,[int]$TimeoutMinutes=25)
$ErrorActionPreference='Stop';$enc=New-Object Text.UTF8Encoding($false);$repo=Split-Path $PSScriptRoot -Parent
if(-not $EvidenceDirectory){$EvidenceDirectory=Join-Path $repo 'evidence/phase-0b-codex-extension-u006'}
$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$session=[IO.Path]::GetFullPath($SessionRoot);if(-not $session.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase)-or(Split-Path $session -Leaf)-notmatch '^dual-pool-extension-probe-[a-f0-9]{32}$'){throw 'UNSAFE_SESSION_ROOT'}
$started=[DateTime]::UtcNow;$deadline=$started.AddMinutes($TimeoutMinutes);$runId=$started.ToString('yyyyMMddTHHmmssfffZ');$secret='SECRET_SENTINEL_'+[Guid]::NewGuid().ToString('N');$prompt='ASTRA_PROMPT_SENTINEL_'+[Guid]::NewGuid().ToString('N')
$dirs=@{ide=Join-Path $session 'ide-user-data';codex=Join-Path $session 'codex-home';ext=Join-Path $session 'extensions';workspace=Join-Path $session 'workspace';rec=Join-Path $session 'recorder';state=Join-Path $session 'state';control=Join-Path $session 'state/control'};$status='BLOCKED';$classification='RUNNING';$stage='INIT';$rec=$null;$port=$null;$capture=$null;$protected=@();$auth=$false;$astra=$false;$failure=$null;$manifestBefore='ABSENT';$manifestAfter='ABSENT'
function HashFile([string]$p){if(Test-Path -LiteralPath $p -PathType Leaf){return(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash};return 'ABSENT'}
function WriteSafe([string]$p,$v){$text=$v|ConvertTo-Json -Depth 30;if($text.Contains($secret)-or$text.Contains($prompt)-or$text-match'(?i)\b[A-Z]:\\'){throw 'UNSAFE_EVIDENCE'};[IO.File]::WriteAllText($p,$text+"`n",$enc)}
function SetStage([string]$name,$metadata=@{}){$script:stage=$name;WriteSafe (Join-Path $dirs.state 'status.json') @{run_id=$runId;stage=$name;metadata=$metadata}}
function ProbeProcesses(){@(Get-CimInstance Win32_Process|Where-Object{$_.Name -eq 'Antigravity IDE.exe'-and$_.CommandLine -like ('*'+$dirs.ide+'*')})}
function OriginalsAlive(){@($protected|Where-Object{-not(Get-Process -Id $_ -ErrorAction SilentlyContinue)}).Count -eq 0}
function WaitControl([string[]]$names,[string]$waitStage){SetStage $waitStage @{allowed_controls=$names};while([DateTime]::UtcNow -lt $deadline){foreach($name in $names){if(Test-Path -LiteralPath (Join-Path $dirs.control $name)){return $name}};Start-Sleep -Milliseconds 500};throw 'USER_ASSISTED_PROBE_TIMEOUT'}
try {
  foreach($dir in $dirs.Values){New-Item -ItemType Directory -Path $dir -Force|Out-Null};New-Item -ItemType Directory -Path $EvidenceDirectory -Force|Out-Null;$realConfig=Join-Path $env:USERPROFILE '.codex/config.toml';$realSettings=Join-Path $env:APPDATA 'Antigravity IDE/User/settings.json';$realConfigBefore=HashFile $realConfig;$realSettingsBefore=HashFile $realSettings;SetStage 'PRECHECK' @{temporary_auth_allowed=$true}
  $ideRoot=Join-Path $env:LOCALAPPDATA 'Programs/Antigravity IDE';$ideExe=Join-Path $ideRoot 'Antigravity IDE.exe';$cli=Join-Path $ideRoot 'resources/app/out/cli.js';$ideCmd=Join-Path $ideRoot 'bin/antigravity-ide.cmd';$extRoot=Join-Path $env:USERPROFILE '.antigravity-ide/extensions';$node=(Get-Command node.exe).Source;foreach($required in @($ideExe,$cli,$ideCmd,$extRoot,$node)){if(-not(Test-Path -LiteralPath $required)){throw 'REQUIRED_PATH_ABSENT'}}
  $help=& $ideCmd --help 2>&1|Out-String;if(-not$help.Contains('--user-data-dir')){throw 'PARALLEL_USER_DATA_UNSUPPORTED'};$source=@(Get-ChildItem -LiteralPath $extRoot -Directory|Where-Object{$_.Name -like 'openai.chatgpt-*'});if($source.Count -ne 1){throw 'EXTENSION_DISCOVERY_FAILED'};$source=$source[0];$manifestBefore=HashFile (Join-Path $source.FullName 'package.json');Copy-Item -LiteralPath $source.FullName -Destination (Join-Path $dirs.ext $source.Name) -Recurse -Force;$manifestAfter=HashFile (Join-Path (Join-Path $dirs.ext $source.Name) 'package.json');if($manifestBefore -ne $manifestAfter){throw 'EXTENSION_SILO_HASH_MISMATCH'};$protected=@(Get-CimInstance Win32_Process|Where-Object{$_.Name -eq 'Antigravity IDE.exe'}|Select-Object -ExpandProperty ProcessId);if($protected.Count -eq 0){throw 'ORIGINAL_IDE_NOT_RUNNING'}
  $recInfo=[Diagnostics.ProcessStartInfo]::new();$recInfo.FileName=$node;$recInfo.Arguments='"'+(Join-Path $PSScriptRoot 'phase0b-extension-recorder-u006.cjs')+'"';$recInfo.UseShellExecute=$false;$recInfo.CreateNoWindow=$true;foreach($item in @{P0B_U006_ROOT=$dirs.rec;P0B_U006_SECRET=$secret;P0B_U006_PROMPT=$prompt}.GetEnumerator()){$recInfo.EnvironmentVariables[$item.Key]=$item.Value};$rec=[Diagnostics.Process]::Start($recInfo);$readyPath=Join-Path $dirs.rec 'ready.json';while(-not(Test-Path $readyPath)-and[DateTime]::UtcNow-lt$started.AddSeconds(15)){Start-Sleep -Milliseconds 100};if(-not(Test-Path $readyPath)){throw 'RECORDER_NOT_READY'};$ready=Get-Content -Raw $readyPath|ConvertFrom-Json;$port=[int]$ready.port;$listeners=@(Get-NetTCPConnection -State Listen -LocalPort $port);if($listeners.Count -ne 1-or$listeners[0].LocalAddress -ne '127.0.0.1'-or$listeners[0].OwningProcess -ne $rec.Id){throw 'RECORDER_OWNERSHIP_FAILED'}
  $toml="model = `"gpt-5.6-sol`"`nmodel_provider = `"dualpool_probe`"`n`n[model_providers.dualpool_probe]`nname = `"Dual Pool Phase 0B U-006`"`nbase_url = `"http://127.0.0.1:$port/v1`"`nwire_api = `"responses`"`nenv_key = `"DUALPOOL_CODEX_KEY`"`n";[IO.File]::WriteAllText((Join-Path $dirs.codex 'config.toml'),$toml,$enc);$launch=[Diagnostics.ProcessStartInfo]::new();$launch.FileName=$ideExe;$launch.UseShellExecute=$false;$launch.EnvironmentVariables['ELECTRON_RUN_AS_NODE']='1';$launch.EnvironmentVariables['VSCODE_DEV']='';$launch.EnvironmentVariables['CODEX_HOME']=$dirs.codex;$launch.EnvironmentVariables['DUALPOOL_CODEX_KEY']=$secret;$launch.Arguments='"'+$cli+'" --new-window --user-data-dir "'+$dirs.ide+'" --extensions-dir "'+$dirs.ext+'" "'+$dirs.workspace+'"';$launcher=[Diagnostics.Process]::Start($launch);$launcher.WaitForExit(10000)|Out-Null;Start-Sleep -Seconds 8;$probe=@(ProbeProcesses);$candidate=@($probe|Where-Object{$protected -notcontains $_.ParentProcessId}|Select-Object -First 1);if($candidate.Count -ne 1-or-not(OriginalsAlive)){throw 'PROBE_ISOLATION_FAILED'}
  $authChoice=WaitControl @('probe-authenticated','probe-auth-not-recognized') 'WAIT_AUTHENTICATION';if($authChoice -eq 'probe-auth-not-recognized'){$classification='CLI_AUTH_NOT_CONSUMED_BY_EXTENSION';throw 'CLI_AUTH_NOT_CONSUMED_BY_EXTENSION'};$auth=$true;[IO.File]::WriteAllText((Join-Path $dirs.state 'astra-prompt.txt'),"Phase 0B Astra synthetic transport check. Reply briefly.`r`n$prompt`r`n",$enc);$choice=WaitControl @('astra-selected','astra-not-visible-authenticated') 'WAIT_PICKER';if($choice -eq 'astra-not-visible-authenticated'){$classification='AUTHENTICATED_ASTRA_NOT_VISIBLE';throw 'ASTRA_NOT_VISIBLE_AUTHENTICATED'};$astra=$true;$null=WaitControl @('astra-sent') 'WAIT_REQUEST';$capturePath=Join-Path $dirs.rec 'capture-u006.json';while(-not(Test-Path $capturePath)-and[DateTime]::UtcNow-lt$deadline){Start-Sleep -Milliseconds 300};if(-not(Test-Path $capturePath)){throw 'REQUEST_CAPTURE_TIMEOUT'};$capture=Get-Content -Raw $capturePath|ConvertFrom-Json;if($capture.model_exact_astra -ne $true){$classification='WIRE_MODEL_NOT_GPT_6_ASTRA';throw 'WIRE_MODEL_NOT_GPT_6_ASTRA'};if($capture.auth_match_status -ne 'PASS'){$classification='SYNTHETIC_AUTH_MISMATCH';throw 'SYNTHETIC_AUTH_MISMATCH'};if($capture.prompt_match_status -ne 'PASS'-or$capture.json_parse_status -ne 'PASS'){$classification='REQUEST_PARSE_OR_PROMPT_FAILED';throw 'REQUEST_PARSE_OR_PROMPT_FAILED'};if(-not$capture.response_closed){throw 'RESPONSE_LIFECYCLE_FAILED'};$classification='PASS';$null=WaitControl @('probe-closed') 'WAIT_PROBE_CLOSE';$status='PASS'
}catch{$classification=if($classification -eq 'RUNNING'){$_.Exception.Message}else{$classification};$failure=@{exception_type=$_.Exception.GetType().FullName;classification=$classification;stage=$stage;script_relative_path='scripts/phase0b-codex-extension-u006-authenticated.ps1';line_number=$_.InvocationInfo.ScriptLineNumber};if($stage -ne 'WAIT_PROBE_CLOSE'){try{$null=WaitControl @('probe-closed') 'WAIT_PROBE_CLOSE'}catch{}}}
finally{if($rec-and-not$rec.HasExited){try{$rec.Kill();$rec.WaitForExit(5000)|Out-Null}catch{}};$remaining=@(ProbeProcesses);$afterConfig=HashFile $realConfig;$afterSettings=HashFile $realSettings;$listenerGone=($null -eq $port -or (@(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue).Count -eq 0));$cleanup=@{probe_process_absent=($remaining.Count -eq 0);original_instance_survived=(OriginalsAlive);recorder_listener_absent=$listenerGone;temporary_root_exists_before_cleanup=$true;temporary_root_removed=$false};if($remaining.Count -eq 0){try{[IO.Directory]::Delete($session,$true);$cleanup.temporary_root_removed=(-not[IO.Directory]::Exists($session))}catch{}};$result=[ordered]@{schema_version='4';test_id='P0B-CX-MODEL-RESOLUTION-001';run_id=$runId;status=$status;classification=$classification;authentication_context_present=$auth;observation_source='user-assisted';astra_selected=$astra;capture=$capture;controls=@{real_config_unchanged=($realConfigBefore -eq $afterConfig);real_settings_unchanged=($realSettingsBefore -eq $afterSettings);installed_extension_manifest_unchanged=($manifestBefore -eq $manifestAfter)};cleanup=$cleanup;failure=$failure;unknowns=@{'U-001'='BLOCKED';'U-002'='BLOCKED';'U-003'='BLOCKED';'U-004'='BLOCKED';'U-005'='PROBED';'U-006'=if($status -eq 'PASS'){'PROBED'}else{'BLOCKED'};'U-007'='PROBED';'U-008'='PARTIAL / UNKNOWN'}};WriteSafe (Join-Path $EvidenceDirectory ('u006-'+$runId+'.json')) $result;Write-Output ('RESULT run_id={0} status={1} classification={2}'-f$runId,$status,$classification)}
if($status -ne 'PASS'){exit 1}
