[CmdletBinding()]
param([switch]$Generate)
$ErrorActionPreference='Stop';$repo=Split-Path $PSScriptRoot -Parent;$e=Join-Path $repo 'evidence/phase-0b-u006-primary-profile';$report='docs/reports/2026-09-19T0715Z-phase-0b-u006-primary-profile.md'
$relative=@('scripts/phase0b-extension-recorder-primary.cjs','scripts/phase0b-u006-primary-watchdog.ps1','scripts/phase0b-u006-primary-restore.ps1','scripts/phase0b-verify-primary-profile.ps1',$report)+@(Get-ChildItem $e -Filter '*.json'|Where-Object{$_.Name -notin @('security-gate.json','evidence-manifest.json')}|ForEach-Object{$_.FullName.Substring($repo.Length+1).Replace('\','/')})
$absolute=@($relative|ForEach-Object{Join-Path $repo $_});$violations=@();$pathPattern='(?i)\b[A-Z]:\\';$secretPatterns=@('(?i)Bearer\s+[A-Za-z0-9._~-]{12,}','(?i)-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----','(?i)(?:access|refresh)[_-]?token\s*[:=]','(?i)\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b')
foreach($file in $absolute){if(-not(Test-Path $file)){throw "MISSING_ARTIFACT:$file"};$text=Get-Content -Raw $file;if($text-match$pathPattern){$violations+='ABSOLUTE_LOCAL_PATH'};foreach($p in $secretPatterns){if($text-match$p){$violations+='SECRET_OR_IDENTITY_PATTERN'}};if($file.EndsWith('.json')){$text|ConvertFrom-Json|Out-Null}}
[scriptblock]::Create((Get-Content -Raw (Join-Path $repo 'scripts/phase0b-u006-primary-watchdog.ps1')))|Out-Null;[scriptblock]::Create((Get-Content -Raw (Join-Path $repo 'scripts/phase0b-u006-primary-restore.ps1')))|Out-Null;node --check (Join-Path $repo 'scripts/phase0b-extension-recorder-primary.cjs')|Out-Null;git -C $repo diff --check|Out-Null;if($violations.Count){throw ('PRIVACY_SCAN_FAILED:'+($violations|Sort-Object -Unique -join ','))}
$gate=[ordered]@{schema_version='1';status='PASS';paths_actually_scanned=$relative;excluded_paths=@('evidence/phase-0b-u006-primary-profile/evidence-manifest.json','evidence/phase-0b-u006-primary-profile/security-gate.json');exclusion_reason='Generated last and verified separately';positive_controls=@{json='PASS';node_syntax='PASS';powershell_syntax='PASS';absolute_path_scan='PASS';secret_privacy_scan='PASS';config_content_scan='PASS';diff_check='PASS'};u005='PROBED';u006='BLOCKED';classification='NORMAL_RELAUNCH_FAILED';cleanup=@{temp_root_removed=$true;config_restore_pass=$true;auth_material_inspected=$false;auth_material_committed=$false;auth_material_hashed=$false}}
if($Generate){$enc=New-Object Text.UTF8Encoding($false);[IO.File]::WriteAllText((Join-Path $e 'security-gate.json'),($gate|ConvertTo-Json -Depth 20)+"`n",$enc);$files=@($absolute+(Join-Path $e 'security-gate.json'));$manifest=@{schema_version='1';status='PASS';artifacts=@($files|ForEach-Object{$h=Get-FileHash $_ -Algorithm SHA256;[ordered]@{path=$_.Substring($repo.Length+1).Replace('\','/');sha256=$h.Hash;size=(Get-Item $_).Length}})};[IO.File]::WriteAllText((Join-Path $e 'evidence-manifest.json'),($manifest|ConvertTo-Json -Depth 20)+"`n",$enc);$check=Get-Content -Raw (Join-Path $e 'evidence-manifest.json')|ConvertFrom-Json;foreach($item in $check.artifacts){if((Get-FileHash (Join-Path $repo $item.path) -Algorithm SHA256).Hash-ne$item.sha256){throw 'MANIFEST_HASH_VERIFY_FAILED'}}}
$gate|ConvertTo-Json -Depth 20
