$ErrorActionPreference='Stop'
$runId=[DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ');$started=[DateTime]::UtcNow
$diagnostic=Join-Path ([IO.Path]::GetTempPath()) 'dual-pool-phase0b-v4-diagnostic.txt';trap{($_|Out-String)|Set-Content -LiteralPath $diagnostic -Encoding UTF8;exit 2}
$tempRoot=Join-Path ([IO.Path]::GetTempPath()) ('dual-pool-phase0b-v4-'+[Guid]::NewGuid().ToString('N'));$codexHome=Join-Path $tempRoot 'codex-home';$capture=Join-Path $tempRoot 'metadata.json';$recorder=Join-Path $tempRoot 'recorder.ps1';$port=Get-Random -Minimum 19100 -Maximum 19900
$secretSentinel='SECRET_SENTINEL_'+[Guid]::NewGuid().ToString('N');$promptSentinel='PROMPT_SENTINEL_'+[Guid]::NewGuid().ToString('N');$owned=@();$proc=$null;$recorderProc=$null;$stdout=New-Object System.Text.StringBuilder;$stderr=New-Object System.Text.StringBuilder
$result=[ordered]@{schema_version='1.0';test_id='P0B-CX-TRANSPORT-001';run_id=$runId;status='FAIL';assertions=[ordered]@{};limitations=@('Synthetic loopback response only; no provider account or user configuration used.')}
function Shape($v,$p){$o=New-Object System.Collections.Generic.List[string];if($null -eq $v){$o.Add($p+':null');return $o};if($v -is [Collections.IEnumerable] -and -not($v -is [string])){$o.Add($p+':array');foreach($x in $v){foreach($y in (Shape $x ($p+'[]'))){$o.Add($y)}};return $o};$ps=@($v.PSObject.Properties);if($ps.Count -gt 0 -and $v -isnot [string] -and $v -isnot [ValueType]){$o.Add($p+':object');foreach($q in $ps){foreach($x in (Shape $q.Value ($p+'.'+$q.Name))){$o.Add($x)}};return $o};$o.Add($p+':'+$v.GetType().Name.ToLowerInvariant());return $o}
try{
  $cmd=Get-Command codex -ErrorAction Stop;$codexPath=$cmd.Source;New-Item -ItemType Directory -Path $codexHome -Force|Out-Null
  $result.environment=[ordered]@{os=[Environment]::OSVersion.VersionString;architecture=[Environment]::GetEnvironmentVariable('PROCESSOR_ARCHITECTURE');codex_version=((&$codexPath --version 2>&1|Select-Object -First 1).ToString());codex_sha256=(Get-FileHash $codexPath -Algorithm SHA256).Hash}
  $old='data: {"type":"response.created"}`n`ndata: {"type":"response.completed"}`n`n';$events=@('data: {"type":"response.created","response":{"id":"resp_phase0b"}}','data: {"type":"response.completed","response":{"id":"resp_phase0b"}}');$sse=($events-join"`n`n")+"`n`n";$oldBytes=[Text.Encoding]::UTF8.GetBytes($old);$sseBytes=[Text.Encoding]::UTF8.GetBytes($sse);$result.harness_selftest=[ordered]@{old_has_lf_lf=([Array]::IndexOf($oldBytes,[byte]10)-ge0);v4_has_lf_lf=([Text.Encoding]::UTF8.GetString($sseBytes).Contains("`n`n"));created_parses=($events[0].Substring(6)|ConvertFrom-Json).type-eq'response.created';completed_parses=($events[1].Substring(6)|ConvertFrom-Json).type-eq'response.completed';content_type='text/event-stream';response_closes_after_final=$true}
  if($result.harness_selftest.old_has_lf_lf-or-not$result.harness_selftest.v4_has_lf_lf-or-not$result.harness_selftest.created_parses-or-not$result.harness_selftest.completed_parses){throw 'HARNESS_SELFTEST_FAIL'}
  @'
param([int]$Port,[string]$Capture,[string]$SecretSentinel,[string]$PromptSentinel)
$ErrorActionPreference='Stop';function Shape($v,$p){$o=New-Object System.Collections.Generic.List[string];if($null -eq $v){$o.Add($p+':null');return $o};if($v -is [Collections.IEnumerable] -and -not($v -is [string])){$o.Add($p+':array');foreach($x in $v){foreach($y in (Shape $x ($p+'[]'))){$o.Add($y)}};return $o};$ps=@($v.PSObject.Properties);if($ps.Count -gt 0 -and $v -isnot [string] -and $v -isnot [ValueType]){$o.Add($p+':object');foreach($q in $ps){foreach($x in (Shape $q.Value ($p+'.'+$q.Name))){$o.Add($x)}};return $o};$o.Add($p+':'+$v.GetType().Name.ToLowerInvariant());return $o}
$l=[Net.HttpListener]::new();$l.Prefixes.Add(('http://127.0.0.1:{0}/'-f$Port));$l.Start();try{while($true){$c=$l.GetContext();$r=$c.Request;if($r.HttpMethod-eq'GET'-and$r.Url.AbsolutePath-eq'/v1/models'){$b=[Text.Encoding]::UTF8.GetBytes('{"data":[{"id":"gpt-6-astra","object":"model"}]}');$c.Response.ContentType='application/json';$c.Response.StatusCode=200;$c.Response.OutputStream.Write($b,0,$b.Length);$c.Response.Close();continue};$body=(New-Object IO.StreamReader($r.InputStream)).ReadToEnd();$j=$body|ConvertFrom-Json;$auth=[string]$r.Headers['Authorization'];$m=[ordered]@{method=$r.HttpMethod;route=$r.Url.AbsolutePath;content_type=$r.ContentType;header_names=@($r.Headers.AllKeys|Sort-Object);model=$j.model;request_shape=@(Shape $j 'body');authorization_header_present=(-not[string]::IsNullOrEmpty($auth));secret_seen_at_expected_ingress=$auth.Contains($SecretSentinel);prompt_seen_at_expected_ingress=$body.Contains($PromptSentinel);raw_body_field_present=$false};$m|ConvertTo-Json -Depth 30|Set-Content $Capture -Encoding UTF8;$events=@('data: {"type":"response.created","response":{"id":"resp_phase0b"}}','data: {"type":"response.completed","response":{"id":"resp_phase0b"}}');$sse=($events-join"`n`n")+"`n`n";$b=[Text.Encoding]::UTF8.GetBytes($sse);$c.Response.ContentType='text/event-stream';$c.Response.StatusCode=200;$c.Response.OutputStream.Write($b,0,$b.Length);$c.Response.Close()}}finally{$l.Stop();$l.Close()}
'@|Set-Content $recorder -Encoding UTF8
  $recorderProc=Start-Process powershell.exe -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$recorder,'-Port',$port,'-Capture',$capture,'-SecretSentinel',$secretSentinel,'-PromptSentinel',$promptSentinel) -PassThru -WindowStyle Hidden;$owned+=$recorderProc.Id;Start-Sleep -Milliseconds 500
  $listeners=@(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue);$result.listener=[ordered]@{address=($listeners.LocalAddress|Select-Object -First 1);port=$port;pid_owns_listener=($listeners.Count-eq1-and$listeners[0].OwningProcess-eq$recorderProc.Id);wildcard_absent=(-not($listeners.LocalAddress-contains'0.0.0.0')-and-not($listeners.LocalAddress-contains'::'))}
  $env:CODEX_HOME=$codexHome;$env:DUALPOOL_CODEX_KEY=$secretSentinel;$prompt='PHASE0B_SYNTHETIC_ONLY '+$promptSentinel;$args=@('exec','--json','--skip-git-repo-check','-m','gpt-6-astra','-c','model_provider="dualpool_codex"','-c','model_providers.dualpool_codex.name="DualPoolPhase0B"','-c',('model_providers.dualpool_codex.base_url="http://127.0.0.1:{0}/v1"'-f$port),'-c','model_providers.dualpool_codex.wire_api="responses"','-c','model_providers.dualpool_codex.env_key="DUALPOOL_CODEX_KEY"',$prompt)
  $si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$codexPath;$si.UseShellExecute=$false;$si.RedirectStandardOutput=$true;$si.RedirectStandardError=$true;$si.Arguments=($args|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ';$proc=[Diagnostics.Process]::new();$proc.StartInfo=$si;$proc.add_OutputDataReceived({param($s,$e)if($null-ne$e.Data){if($stdout.Length-lt32768){[void]$stdout.AppendLine($e.Data)}}});$proc.add_ErrorDataReceived({param($s,$e)if($null-ne$e.Data){if($stderr.Length-lt32768){[void]$stderr.AppendLine($e.Data)}}});[void]$proc.Start();$owned+=$proc.Id;$proc.BeginOutputReadLine();$proc.BeginErrorReadLine();$natural=$proc.WaitForExit(15000);if($natural){$proc.WaitForExit()};$result.process=[ordered]@{pid=$proc.Id;process_pid_owned=$true;natural_exit=$natural;timed_out=(-not$natural);killed_by_harness=$false;exit_code=$null}
  if(-not$natural){$proc.Kill();$proc.WaitForExit();$result.process.killed_by_harness=$true}else{$result.process.exit_code=$proc.ExitCode}
  if(Test-Path $capture){$m=Get-Content -Raw $capture|ConvertFrom-Json;$result.observed=$m}
  $result.stdout=[ordered]@{length_bucket=([Math]::Min(32768,$stdout.Length));stderr_length_bucket=([Math]::Min(32768,$stderr.Length));stderr_nonempty=($stderr.Length-gt0)}
}catch{$result.failure_classification=$_.Exception.Message}finally{
  if($recorderProc-and-not$recorderProc.HasExited){$recorderProc.Kill();$recorderProc.WaitForExit()};Remove-Item Env:CODEX_HOME -ErrorAction SilentlyContinue;Remove-Item Env:DUALPOOL_CODEX_KEY -ErrorAction SilentlyContinue
  $persisted=@(Get-ChildItem $tempRoot -File -Recurse -ErrorAction SilentlyContinue);$scanParts=New-Object System.Collections.Generic.List[string];foreach($file in $persisted){try{[void]$scanParts.Add([Text.Encoding]::UTF8.GetString([IO.File]::ReadAllBytes($file.FullName)))}catch{}};$scanText=$scanParts -join "`n";$secretFound=$scanText.Contains($secretSentinel);$promptFound=$scanText.Contains($promptSentinel);$result.secret_scan=[ordered]@{secret_sentinel_found_in_persisted_files=$secretFound;prompt_sentinel_found_in_persisted_files=$promptFound;match_count=0};if($secretFound){$result.secret_scan.match_count++};if($promptFound){$result.secret_scan.match_count++};$result.cleanup=[ordered]@{recorder_terminated=($null -eq $recorderProc -or $recorderProc.HasExited);listener_after=@(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue).Count;owned_processes_after=@($owned|Where-Object{Get-Process -Id $_ -ErrorAction SilentlyContinue}).Count}
  if($null -eq $result.process){$result.process=[ordered]@{natural_exit=$false;timed_out=$false;killed_by_harness=$false;exit_code=$null}};if($null -eq $result.listener){$result.listener=[ordered]@{address=$null;pid_owns_listener=$false;wildcard_absent=$false}};$result.assertions.harness_selftest=($result.harness_selftest.v4_has_lf_lf -and $result.harness_selftest.created_parses -and $result.harness_selftest.completed_parses);$result.assertions.listener_loopback_owned=($result.listener.address -eq '127.0.0.1' -and $result.listener.pid_owns_listener -and $result.listener.wildcard_absent);$result.assertions.request_captured=($null -ne $result.observed -and $result.observed.method -eq 'POST' -and $result.observed.route -eq '/v1/responses' -and $result.observed.model -eq 'gpt-6-astra');$result.assertions.sentinels_verified_in_memory=($null -ne $result.observed -and $result.observed.secret_seen_at_expected_ingress -and $result.observed.prompt_seen_at_expected_ingress);$result.assertions.natural_lifecycle=($result.process.natural_exit -and -not $result.process.timed_out -and -not $result.process.killed_by_harness);$result.assertions.cleanup=($result.cleanup.recorder_terminated -and $result.cleanup.listener_after -eq 0 -and $result.cleanup.owned_processes_after -eq 0);$result.assertions.no_sentinel_persisted=(-not $result.secret_scan.secret_sentinel_found_in_persisted_files -and -not $result.secret_scan.prompt_sentinel_found_in_persisted_files);$result.status='PASS';foreach($v in $result.assertions.Values){if($v -ne $true){$result.status='FAIL'}};$result.ended_at=[DateTime]::UtcNow.ToString('o');$result.duration_ms=([DateTime]::UtcNow-$started).TotalMilliseconds;Remove-Item $tempRoot -Recurse -Force -ErrorAction SilentlyContinue;$result.temp_root_removed=(-not(Test-Path $tempRoot));$out=Join-Path (Get-Location) ('evidence/2026-09-18T1953Z-phase-0b-reversible-compatibility/codex-cli-transport-v4-'+$runId+'.json');$result|ConvertTo-Json -Depth 30|Set-Content $out -Encoding UTF8
};if($result.status-ne'PASS'){exit 1}
