[CmdletBinding()]
param([switch]$Generate)
$ErrorActionPreference='Stop';$repo=Split-Path $PSScriptRoot -Parent;$e=Join-Path $repo 'evidence/phase-0b-codex-extension-v2';$report=Join-Path $repo 'docs/reports/2026-09-19T0400Z-phase-0b-extension-parser-repair.md';$result=Get-ChildItem -LiteralPath $e -Filter 'extension-baseline-*.json'|Sort-Object LastWriteTime|Select-Object -Last 1
$paths=@('scripts/phase0b-extension-recorder-v2.cjs','scripts/phase0b-codex-extension-baseline-v2.ps1','scripts/phase0b-verify-extension-v2.ps1','docs/reports/2026-09-19T0400Z-phase-0b-extension-parser-repair.md','evidence/phase-0b-codex-extension-v2/audit-correction.json',$result.FullName.Substring($repo.Length+1))
$abs=@($paths|ForEach-Object{Join-Path $repo $_});$forbidden=@(('body_'+'prefix_'+'hex'),('body_'+'prefix_'+'base64'),('body_'+'suffix_'+'hex'),('body_'+'fragment'),('raw_'+'body'),('body_'+'text'),('request_'+'body'),('response_'+'body'),('raw_'+'headers'),('raw_'+'stdout'),('raw_'+'stderr'))
$violations=New-Object Collections.Generic.List[string];foreach($p in $abs){if(-not(Test-Path -LiteralPath $p)){throw "MISSING_SCOPE_FILE:$p"};$text=Get-Content -Raw -LiteralPath $p;foreach($needle in $forbidden){if($text.Contains($needle)){[void]$violations.Add($p+':FORBIDDEN_METADATA_FIELD')}}}
$r=Get-Content -Raw $result.FullName|ConvertFrom-Json;if($r.classification -ne 'BASELINE_MODEL_MISMATCH'){throw 'UNEXPECTED_AUTHORITATIVE_CLASSIFICATION'};if($r.baseline_request.json_parse_status -ne 'PASS' -or $r.baseline_request.shape_summary_status -ne 'PASS'){throw 'PARSER_GATE_FAILED'};if($r.baseline_request.auth_match_status -ne 'PASS' -or $r.baseline_request.prompt_match_status -ne 'PASS'){throw 'INGRESS_GATE_FAILED'};if($r.cleanup.probe_process_absent -ne $true -or $r.cleanup.recorder_listener_absent -ne $true -or $r.cleanup.original_instance_survived -ne $true -or $r.cleanup.temporary_root_removed -ne $true){throw 'CLEANUP_GATE_FAILED'};if($violations.Count -gt 0){throw ('SECURITY_SCAN_FAILED:'+($violations -join ','))}
$jsonFiles=@($abs|Where-Object{$_ -match '\.json$'});foreach($p in $jsonFiles){Get-Content -Raw $p|ConvertFrom-Json|Out-Null};[scriptblock]::Create((Get-Content -Raw (Join-Path $repo 'scripts/phase0b-codex-extension-baseline-v2.ps1')))|Out-Null;node --check (Join-Path $repo 'scripts/phase0b-extension-recorder-v2.cjs')|Out-Null;git -C $repo diff --check|Out-Null
$out=[ordered]@{schema_version='2';status='PASS';paths_actually_scanned=$paths;positive_controls=@{forbidden_metadata_field_scan='PASS';json_schema='PASS';parser_syntax='PASS';diff_check='PASS'};authoritative_result=$result.Name;classification=$r.classification;u005=$r.unknowns.'U-005';u006=$r.unknowns.'U-006';cleanup=$r.cleanup};if($Generate){$enc=New-Object Text.UTF8Encoding($false);$json=$out|ConvertTo-Json -Depth 20;[IO.File]::WriteAllText((Join-Path $e 'security-gate.json'),$json+"`n",$enc);[IO.File]::WriteAllText((Join-Path $e 'evidence-manifest.json'),($out|ConvertTo-Json -Depth 20)+"`n",$enc)};$out|ConvertTo-Json -Depth 20
