[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$SessionRoot,[string]$EvidenceDirectory,[int]$TimeoutMinutes=25)
$ErrorActionPreference='Stop';$enc=New-Object Text.UTF8Encoding($false);$repo=Split-Path $PSScriptRoot -Parent;if(-not$EvidenceDirectory){$EvidenceDirectory=Join-Path $repo 'evidence/phase-0b-codex-u006-auth-reuse'};$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$session=[IO.Path]::GetFullPath($SessionRoot);if(-not$session.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase)-or(Split-Path $session -Leaf)-notmatch '^dual-pool-u006-[a-f0-9]{32}$'){throw'UNSAFE_SESSION_ROOT'}
$started=[DateTime]::UtcNow;$runId=$started.ToString('yyyyMMddTHHmmssfffZ');$codexHome=Join-Path $session 'codex-home';$authSource=Join-Path (Join-Path $env:USERPROFILE '.codex') 'auth.json';$authDest=Join-Path $codexHome 'auth.json';New-Item -ItemType Directory -Path $codexHome,(Join-Path $session 'state') -Force|Out-Null;New-Item -ItemType Directory -Path $EvidenceDirectory -Force|Out-Null
function Status([string]$codexHomeArg){$old=$env:CODEX_HOME;$oldEa=$ErrorActionPreference;$env:CODEX_HOME=$codexHomeArg;$ErrorActionPreference='Continue';try{$raw=(& codex login status 2>&1|Out-String);return [ordered]@{authenticated=($raw-match'(?i)chatgpt');auth_method=if($raw-match'(?i)chatgpt'){'CHATGPT'}elseif($raw-match'(?i)api.?key'){'API_KEY'}else{'OTHER'}}}finally{$ErrorActionPreference=$oldEa;$env:CODEX_HOME=$old}}
function WriteSafe([string]$p,$v){$text=$v|ConvertTo-Json -Depth 20;if($text-match'(?i)\b[A-Z]:\\'-or$text-match'(?i)Bearer\s+[A-Za-z0-9._~-]{12,}'){throw'UNSAFE_BOOTSTRAP_EVIDENCE'};[IO.File]::WriteAllText($p,$text+"`n",$enc)}
$method='NONE';$temporary=$null;if(Test-Path -LiteralPath $authSource -PathType Leaf){Copy-Item -LiteralPath $authSource -Destination $authDest -Force;$method='OPAQUE_AUTH_FILE_COPY';$temporary=Status $codexHome}
if(-not$temporary-or-not$temporary.authenticated){$temporary=Status $codexHome;if(-not$temporary.authenticated){$method='OFFICIAL_TEMP_CODEX_LOGIN';$login=[Diagnostics.ProcessStartInfo]::new();$login.FileName='powershell.exe';$login.Arguments='-NoProfile -NoExit -Command "$env:CODEX_HOME=\'''+$codexHome+'\''; codex login"';$login.UseShellExecute=$true;$login.EnvironmentVariables['CODEX_HOME']=$codexHome;$p=[Diagnostics.Process]::Start($login);$null=Read-Host 'After official temporary Codex login completes, press Enter';$temporary=Status $codexHome}}
$bootstrap=[ordered]@{schema_version='1';test_id='P0B-CX-AUTH-BOOTSTRAP-001';run_id=$runId;auth_source_method=$method;temporary_auth_status=if($temporary.authenticated){'AUTHENTICATED_CHATGPT'}else{'NOT_AUTHENTICATED'};auth_material_read=$false;auth_material_logged=$false;auth_material_committed=$false;auth_material_hashed=$false;auth_path_in_approved_temp_root=$true;auth_path_in_repository=$false};WriteSafe (Join-Path $EvidenceDirectory ('auth-bootstrap-'+$runId+'.json')) $bootstrap;if(-not$temporary.authenticated){[IO.Directory]::Delete($session,$true);exit 2}
$childSession=Join-Path ([IO.Path]::GetTempPath()) ('dual-pool-extension-probe-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path (Join-Path $childSession 'codex-home') -Force|Out-Null;Copy-Item -LiteralPath $authDest -Destination (Join-Path $childSession 'codex-home/auth.json') -Force
$childArgs=@('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $PSScriptRoot 'phase0b-codex-extension-u006-authenticated.ps1'),'-SessionRoot',$childSession,'-EvidenceDirectory',$EvidenceDirectory,'-TimeoutMinutes',$TimeoutMinutes);& powershell.exe @childArgs;$exit=$LASTEXITCODE;if([IO.Directory]::Exists($session)){[IO.Directory]::Delete($session,$true)};exit $exit
