[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$SessionRoot,[string]$EvidenceDirectory,[int]$TimeoutMinutes=15)
$ErrorActionPreference='Stop'; $utf8=New-Object Text.UTF8Encoding($false); $repo=Split-Path $PSScriptRoot -Parent
if(-not $EvidenceDirectory){$EvidenceDirectory=Join-Path $repo 'evidence/phase-0b-codex-extension-v2'}
$tmp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()); $session=[IO.Path]::GetFullPath($SessionRoot)
if(-not $session.StartsWith($tmp,[StringComparison]::OrdinalIgnoreCase) -or (Split-Path $session -Leaf) -notmatch '^dual-pool-extension-probe-[a-f0-9]{32}$'){throw 'UNSAFE_SESSION_ROOT'}
$started=[DateTime]::UtcNow; $runId=$started.ToString('yyyyMMddTHHmmssfffZ'); $testId='P0B-CX-EXTENSION-BASELINE-V2-001'; $deadline=$started.AddMinutes($TimeoutMinutes)
$dirs=@{ide=Join-Path $session 'ide-user-data'; codex=Join-Path $session 'codex-home'; ext=Join-Path $session 'extensions'; workspace=Join-Path $session 'workspace'; recorder=Join-Path $session 'recorder'; state=Join-Path $session 'state'; control=Join-Path $session 'state/control'}
$statusPath=Join-Path $dirs.state 'status.json'; $secret='SECRET_SENTINEL_'+[Guid]::NewGuid().ToString('N'); $prompt='BASELINE_PROMPT_SENTINEL_'+[Guid]::NewGuid().ToString('N'); $model='gpt-5.6-sol'; $events=@(); $recorder=$null; $port=$null; $stage='INIT'; $classification='RUNNING'; $status='BLOCKED'; $capture=$null; $userBaseline=$false; $protected=@(); $probePids=@(); $probeRoot=$null
$realConfig=Join-Path $env:USERPROFILE '.codex/config.toml'; $realSettings=Join-Path $env:APPDATA 'Antigravity IDE/User/settings.json'; $sourceExt=$null; $manifestBefore='ABSENT'; $manifestAfter='ABSENT'; $flags=@{}
function Hash([string]$p){if(Test-Path -LiteralPath $p -PathType Leaf){return (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash};return 'ABSENT'}
function Json([string]$p,$v){$s=$v|ConvertTo-Json -Depth 40;if(($secret.Length -gt 8 -and $s.Contains($secret)) -or ($prompt.Length -gt 8 -and $s.Contains($prompt))){throw 'SENTINEL_IN_EVIDENCE'};[IO.File]::WriteAllText($p,$s+"`n",$utf8)}
function State([string]$s,$m=@{}){$script:stage=$s;Json $statusPath @{run_id=$runId;test_id=$testId;stage=$s;updated_at=[DateTime]::UtcNow.ToString('o');metadata=$m}}
function Event([string]$t,$m=@{}){$event=[pscustomobject][ordered]@{timestamp=[DateTime]::UtcNow.ToString('o');event_type=$t;metadata=$m};$script:events=@($script:events)+$event;$payload=[ordered]@{schema_version='2';run_id=$runId;test_id=$testId;events=@($script:events)};$text=$payload|ConvertTo-Json -Depth 40;if($text.Contains($secret)-or$text.Contains($prompt)){throw 'SENTINEL_IN_EVIDENCE'};[IO.File]::WriteAllText((Join-Path $EvidenceDirectory ('probe-events-'+$runId+'.json')),$text+"`n",$utf8)}
function Probe(){@(Get-CimInstance Win32_Process|Where-Object{$_.Name -eq 'Antigravity IDE.exe' -and $_.CommandLine -like ('*'+$dirs.ide+'*')})}
function OriginalsAlive(){@($protected|Where-Object{-not(Get-Process -Id $_ -ErrorAction SilentlyContinue)}).Count -eq 0}
function WaitControl([string]$name){State 'WAIT_BASELINE_REQUEST' @{allowed_control=$name};while([DateTime]::UtcNow -lt $deadline){if(Test-Path -LiteralPath (Join-Path $dirs.control $name)){return $true};Start-Sleep -Milliseconds 500};throw 'USER_ASSISTED_PROBE_TIMEOUT'}
function WaitFile([string]$p){while(-not(Test-Path -LiteralPath $p)-and[DateTime]::UtcNow-lt$deadline){Start-Sleep -Milliseconds 250};if(-not(Test-Path -LiteralPath $p)){throw 'RECORDER_CAPTURE_TIMEOUT'};return Get-Content -Raw -LiteralPath $p|ConvertFrom-Json}
try {
  foreach($d in $dirs.Values){New-Item -ItemType Directory -Path $d -Force|Out-Null};New-Item -ItemType Directory -Path $EvidenceDirectory -Force|Out-Null
  $configBefore=Hash $realConfig;$settingsBefore=Hash $realSettings;State 'PRECHECK' @{baseline_only=$true}
  $ideRoot=Join-Path $env:LOCALAPPDATA 'Programs/Antigravity IDE';$ideExe=Join-Path $ideRoot 'Antigravity IDE.exe';$cli=Join-Path $ideRoot 'resources/app/out/cli.js';$cmd=Join-Path $ideRoot 'bin/antigravity-ide.cmd';$extRoot=Join-Path $env:USERPROFILE '.antigravity-ide/extensions';$node=(Get-Command node.exe).Source
  foreach($p in @($ideExe,$cli,$cmd,$extRoot,$node)){if(-not(Test-Path -LiteralPath $p)){throw 'REQUIRED_INSTALLATION_PATH_ABSENT'}}
  $help=& $cmd --help 2>&1|Out-String;$flags=@{user_data_dir=$help.Contains('--user-data-dir');extensions_dir=$help.Contains('--extensions-dir');new_window=$help.Contains('--new-window')};if(-not$flags.user_data_dir){throw 'PARALLEL_USER_DATA_UNSUPPORTED'}
  $catalog=(& codex debug models --bundled|ConvertFrom-Json).models;if(@($catalog|Where-Object { $_.slug -eq $model -and $_.visibility -eq 'list' }).Count -ne 1){throw 'BASELINE_MODEL_PRECHECK_FAILED'}
  $sourceExt=@(Get-ChildItem -LiteralPath $extRoot -Directory|Where-Object{$_.Name-like 'openai.chatgpt-*'});if($sourceExt.Count-ne 1){throw 'OPENAI_EXTENSION_DISCOVERY_FAILED'};$pkg=Get-Content -Raw (Join-Path $sourceExt[0].FullName 'package.json')|ConvertFrom-Json;$manifestBefore=Hash (Join-Path $sourceExt[0].FullName 'package.json');Copy-Item -LiteralPath $sourceExt[0].FullName -Destination (Join-Path $dirs.ext $sourceExt[0].Name) -Recurse -Force;$manifestAfter=Hash (Join-Path (Join-Path $dirs.ext $sourceExt[0].Name) 'package.json');if($manifestBefore-ne$manifestAfter){throw 'EXTENSION_SILO_HASH_MISMATCH'}
  $protected=@(Get-CimInstance Win32_Process|Where-Object{$_.Name-eq'Antigravity IDE.exe'}|Select-Object -ExpandProperty ProcessId);if($protected.Count-eq 0){throw 'ORIGINAL_IDE_NOT_RUNNING'};Event 'PRECHECK_PASS' @{flags=$flags;initial_model_observed=$true;protected_process_count=$protected.Count};Event 'EXTENSION_ISOLATION_PASS' @{manifest_hash_match=$true;temporary_silo=$true}
  $recInfo=[Diagnostics.ProcessStartInfo]::new();$recInfo.FileName=$node;$recInfo.Arguments='"'+(Join-Path $PSScriptRoot 'phase0b-extension-recorder-v2.cjs')+'"';$recInfo.UseShellExecute=$false;$recInfo.CreateNoWindow=$true;foreach($kv in @{P0B_V2_ROOT=$dirs.recorder;P0B_V2_SECRET=$secret;P0B_V2_PROMPT=$prompt;P0B_V2_BASELINE_MODEL=$model}.GetEnumerator()){$recInfo.EnvironmentVariables[$kv.Key]=$kv.Value};$recorder=[Diagnostics.Process]::Start($recInfo)
  $readyPath=Join-Path $dirs.recorder 'ready.json';while(-not(Test-Path $readyPath)-and[DateTime]::UtcNow-lt$started.AddSeconds(15)){Start-Sleep -Milliseconds 100};if(-not(Test-Path $readyPath)){throw 'RECORDER_NOT_READY'};$ready=Get-Content -Raw $readyPath|ConvertFrom-Json;$port=[int]$ready.port;$self=Get-Content -Raw (Join-Path $dirs.recorder 'self-test.json')|ConvertFrom-Json;if($self.status-ne'PASS'){throw 'RECORDER_SELF_TEST_FAILED'};$listeners=@(Get-NetTCPConnection -State Listen -LocalPort $port);if($listeners.Count-ne 1-or$listeners[0].LocalAddress-ne'127.0.0.1'-or$listeners[0].OwningProcess-ne$recorder.Id){throw 'RECORDER_OWNERSHIP_FAILED'};Event 'RECORDER_READY' @{loopback_only=$true;self_test_pass=$true;one_request_only=$true}
  $toml="model = `"$model`"`nmodel_provider = `"dualpool_probe`"`n`n[model_providers.dualpool_probe]`nname = `"Dual Pool Phase 0B`"`nbase_url = `"http://127.0.0.1:$port/v1`"`nwire_api = `"responses`"`nenv_key = `"DUALPOOL_CODEX_KEY`"`n";[IO.File]::WriteAllText((Join-Path $dirs.codex 'config.toml'),$toml,$utf8)
  $li=[Diagnostics.ProcessStartInfo]::new();$li.FileName=$ideExe;$li.UseShellExecute=$false;$li.EnvironmentVariables['ELECTRON_RUN_AS_NODE']='1';$li.EnvironmentVariables['VSCODE_DEV']='';$li.EnvironmentVariables['CODEX_HOME']=$dirs.codex;$li.EnvironmentVariables['DUALPOOL_CODEX_KEY']=$secret;$li.Arguments='"'+$cli+'" --new-window --user-data-dir "'+$dirs.ide+'" --extensions-dir "'+$dirs.ext+'" "'+$dirs.workspace+'"';$launcher=[Diagnostics.Process]::Start($li);$launcher.WaitForExit(10000)|Out-Null;Start-Sleep -Seconds 8
  $probe=@(Probe);$probePids=@($probe|Select-Object -ExpandProperty ProcessId);$candidate=@($probe|Where-Object{$protected-notcontains$_.ParentProcessId}|Sort-Object CreationDate|Select-Object -First 1);if($probe.Count-eq 0-or$candidate.Count-ne 1){throw 'ANTIGRAVITY_SINGLE_INSTANCE_REUSE'};$probeRoot=[int]$candidate[0].ProcessId;if(-not(OriginalsAlive)){throw 'ORIGINAL_IDE_PROCESS_LOST'};Event 'PROBE_IDE_STARTED' @{probe_root_pid=$probeRoot;process_count=$probePids.Count;original_instance_alive=$true}
  [IO.File]::WriteAllText((Join-Path $dirs.state 'baseline-prompt.txt'),"Phase 0B baseline synthetic transport check. Reply briefly.`r`n$prompt`r`n",$utf8);WaitControl 'baseline-sent'|Out-Null;$userBaseline=$true;Event 'BASELINE_USER_ACTION' @{observation_source='user-assisted';request_ordinal=1};$capture=WaitFile (Join-Path $dirs.recorder 'capture-1.json')
  if(-not $capture.transport_body_received){$classification='TRANSPORT_BODY_NOT_RECEIVED';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.content_decode_status -ne 'PASS'){$classification=$capture.content_decode_status;throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.utf8_status -ne 'PASS'){$classification='UTF8_DECODE_FAILED';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.json_parse_status -ne 'PASS'){$classification='JSON_PARSE_FAILED';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.model_extract_status -ne 'PASS'){$classification='MODEL_FIELD_ABSENT_OR_NOT_STRING';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.model_match_status -ne 'PASS'){$classification='BASELINE_MODEL_MISMATCH';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.auth_match_status -ne 'PASS'){$classification='SYNTHETIC_AUTH_MISMATCH';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.prompt_match_status -ne 'PASS'){$classification='PROMPT_SENTINEL_NOT_FOUND';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if($capture.shape_summary_status -ne 'PASS'){$classification='STRUCTURE_SANITIZER_FAILED';throw 'BASELINE_ACCEPTANCE_FAILED'}
  if(-not $capture.response_closed -or $capture.method -ne 'POST' -or $capture.route -ne '/v1/responses' -or $capture.content_encoding -ne 'identity'){$classification='RESPONSE_LIFECYCLE_FAILED';throw 'BASELINE_ACCEPTANCE_FAILED'}
  Event 'BASELINE_REQUEST_CAPTURED' @{request_ordinal=1;route_responses=$true;auth_match=$true;encoding_identity=$true;utf8=$true;json=$true;model=$true;prompt=$true;sanitizer=$true};State 'WAIT_PROBE_CLOSE' @{allowed_control='probe-closed'};WaitControl 'probe-closed'|Out-Null;$status='PASS';$classification='PASS'
}catch{$failure=@{classification=if($classification-eq'RUNNING'){$_.Exception.Message}else{$classification};stage=$stage;line=$_.InvocationInfo.ScriptLineNumber;position=$_.InvocationInfo.PositionMessage};$classification=$failure.classification;if($stage-ne'WAIT_PROBE_CLOSE'){try{State 'WAIT_PROBE_CLOSE' @{allowed_control='probe-closed';failure=$failure.classification};WaitControl 'probe-closed'|Out-Null}catch{}}}
finally{
  if($recorder-and-not$recorder.HasExited){try{$recorder.Kill();$recorder.WaitForExit(5000)|Out-Null}catch{$status='BLOCKED';$failure=@{classification='RECORDER_CLEANUP_FAILED';stage='CLEANUP'}}};$remaining=@(Probe);$listenerAfter=if($null-eq$port){0}else{@(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue).Count};$configAfter=Hash $realConfig;$settingsAfter=Hash $realSettings;$manifestFinal=if($sourceExt.Count-eq 1){Hash (Join-Path $sourceExt[0].FullName 'package.json')}else{'UNKNOWN'};$cleanup=@{probe_process_absent=($remaining.Count-eq 0);recorder_listener_absent=($listenerAfter-eq 0);original_instance_survived=(OriginalsAlive);temporary_root_removed=$false}
  if($remaining.Count-eq 0){try{[IO.Directory]::Delete($session,$true);$cleanup.temporary_root_removed=(-not[IO.Directory]::Exists($session))}catch{$status='BLOCKED';$failure=@{classification='TEMP_CLEANUP_FAILED';stage='CLEANUP'}}};$u005=if($capture-and$status-eq'PASS'){'PROBED'}else{'PARTIAL / UNKNOWN'};$result=[ordered]@{schema_version='3';test_id=$testId;run_id=$runId;status=$status;classification=$classification;started_at=$started.ToString('o');ended_at=[DateTime]::UtcNow.ToString('o');environment=@{model=$model;extension_id='openai.chatgpt';extension_version=if($pkg){$pkg.version}else{$null}};preflight=@{flags=$flags;extension_manifest_hash_match=($manifestBefore-eq$manifestAfter)};isolation=@{probe_root_pid=$probeRoot;original_instance_remained_alive=(OriginalsAlive);temporary_user_data=$true;temporary_codex_home=$true;temporary_extension_silo=$true};user_observation=@{source='user-assisted';baseline_sent=$userBaseline};baseline_request=$capture;controls=@{real_config_sha256_before=$configBefore;real_config_sha256_after=$configAfter;real_config_unchanged=($configBefore-eq$configAfter);real_settings_sha256_before=$settingsBefore;real_settings_sha256_after=$settingsAfter;real_settings_unchanged=($settingsBefore-eq$settingsAfter);installed_extension_manifest_sha256_before=$manifestBefore;installed_extension_manifest_sha256_after=$manifestFinal;installed_extension_unchanged=($manifestBefore-eq$manifestFinal)};cleanup=$cleanup;failure=$failure;unknowns=@{'U-001'='BLOCKED';'U-002'='BLOCKED';'U-003'='BLOCKED';'U-004'='BLOCKED';'U-005'=$u005;'U-006'='BLOCKED';'U-007'='PROBED';'U-008'='PARTIAL / UNKNOWN'}};New-Item -ItemType Directory -Path $EvidenceDirectory -Force|Out-Null;Json (Join-Path $EvidenceDirectory ('extension-baseline-'+$runId+'.json')) $result;Write-Output ('RESULT run_id={0} status={1} classification={2}'-f$runId,$status,$classification)
}
if($status-ne'PASS'){exit 1}
