[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$SessionRoot,[string]$EvidenceDirectory,[int]$TimeoutMinutes=25)
$ErrorActionPreference='Stop';$enc=New-Object Text.UTF8Encoding($false);$repo=Split-Path $PSScriptRoot -Parent
if(-not$EvidenceDirectory){$EvidenceDirectory=Join-Path $repo 'evidence/phase-0b-u006-profile-clone'}
$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$session=[IO.Path]::GetFullPath($SessionRoot);if(-not$session.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase)-or(Split-Path $session -Leaf)-notmatch '^dual-pool-u006-profile-[a-f0-9]{32}$'){throw 'UNSAFE_SESSION_ROOT'}
$started=[DateTime]::UtcNow;$runId=$started.ToString('yyyyMMddTHHmmssfffZ');$clone=Join-Path $session 'user-data';$child=Join-Path $temp ('dual-pool-extension-probe-'+[Guid]::NewGuid().ToString('N'));$status='BLOCKED';$classification='RUNNING';$sourceDiscovery='UNKNOWN';$copyExit=$null;$childExit=$null;$childResult=$null;$protected=@()
function WriteSafe([string]$p,$v){$text=$v|ConvertTo-Json -Depth 30;if($text-match'(?i)\b[A-Z]:\\'){throw 'UNSAFE_EVIDENCE'};[IO.File]::WriteAllText($p,$text+"`n",$enc)}
function DiscoverProfile(){
  $explicit=@();foreach($p in @(Get-CimInstance Win32_Process|Where-Object{$_.Name -eq 'Antigravity IDE.exe'})){if($p.CommandLine -match '(?i)--user-data-dir\s+"([^"]+)"'){$explicit+=$Matches[1]}elseif($p.CommandLine -match '(?i)--user-data-dir\s+(\S+)'){$explicit+=$Matches[1]}}
  foreach($candidate in $explicit){if([IO.Directory]::Exists($candidate)){return [pscustomobject]@{path=$candidate;kind='EXPLICIT_USER_DATA_DIR'}}}
  $default=Join-Path $env:APPDATA 'Antigravity IDE';if([IO.Directory]::Exists($default)){return [pscustomobject]@{path=$default;kind='DEFAULT_PRODUCT_USER_DATA'}};throw 'SOURCE_PROFILE_ABSENT'
}
function CopyOpaque([string]$source,[string]$destination){New-Item -ItemType Directory -Path $destination -Force|Out-Null;$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName='robocopy.exe';$psi.Arguments='"'+$source+'" "'+$destination+'" /E /COPY:DAT /DCOPY:DAT /XJ /R:0 /W:0 /NFL /NDL /NP /NJH /NJS';$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$p=[Diagnostics.Process]::Start($psi);$null=$p.StandardOutput.ReadToEnd();$null=$p.StandardError.ReadToEnd();$p.WaitForExit();return $p.ExitCode}
try {
  New-Item -ItemType Directory -Path $session,$EvidenceDirectory -Force|Out-Null;$protected=@(Get-CimInstance Win32_Process|Where-Object{$_.Name -eq 'Antigravity IDE.exe'}|Select-Object -ExpandProperty ProcessId);if($protected.Count -eq 0){throw 'ORIGINAL_IDE_NOT_RUNNING'};$profile=DiscoverProfile;$sourceDiscovery=$profile.kind;$copyExit=CopyOpaque $profile.path $clone;if($copyExit -ge 8){$classification='HOT_PROFILE_CLONE_INCOMPLETE';throw 'HOT_PROFILE_CLONE_INCOMPLETE'}
  $childArgs=@('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $PSScriptRoot 'phase0b-codex-extension-u006-authenticated.ps1'),'-SessionRoot',$child,'-UserDataDirSource',$clone,'-EvidenceDirectory',$EvidenceDirectory,'-TimeoutMinutes',$TimeoutMinutes);$cp=Start-Process powershell.exe -WindowStyle Hidden -PassThru -ArgumentList $childArgs;$cp.WaitForExit();$childExit=$cp.ExitCode;$childResult=@(Get-ChildItem -LiteralPath $EvidenceDirectory -Filter 'u006-*.json'|Sort-Object LastWriteTime|Select-Object -Last 1|ForEach-Object{Get-Content -Raw $_.FullName|ConvertFrom-Json})|Select-Object -First 1;if($childExit -eq 0){$status='PASS';$classification='PASS'}else{$classification=if($childResult){$childResult.classification}else{'CLONED_AUTH_STATE_NOT_RECOGNIZED'}}
}catch{$classification=if($classification -eq 'RUNNING'){$_.Exception.Message}else{$classification}}
finally{$probeAbsent=(-not(Get-Process -Id @($childResult|ForEach-Object{0}) -ErrorAction SilentlyContinue));$cloneBefore=[IO.Directory]::Exists($session);$cloneRemoved=$false;if([IO.Directory]::Exists($session)){try{[IO.Directory]::Delete($session,$true);$cloneRemoved=(-not[IO.Directory]::Exists($session))}catch{}};$result=[ordered]@{schema_version='1';test_id='P0B-CX-PROFILE-CLONE-001';run_id=$runId;clone_mode='HOT';source_profile_discovery=$sourceDiscovery;source_profile_present=$true;auth_profile_copy_mode='OPAQUE_FULL_PROFILE';authentication_clone_recognized=if($childResult){[bool]$childResult.authentication_context_present}else{$false};astra_visible=if($childResult){if($childResult.classification -eq 'AUTHENTICATED_ASTRA_NOT_VISIBLE'){$false}else{$null}}else{$null};astra_selected=if($childResult){[bool]$childResult.astra_selected}else{$false};wire_route=if($childResult -and $childResult.capture){$childResult.capture.route}else{$null};wire_model=if($childResult -and $childResult.capture){$childResult.capture.model}else{$null};custom_provider_retained=if($childResult -and $childResult.capture){$true}else{$false};auth_sentinel_match=if($childResult -and $childResult.capture){$childResult.capture.auth_match_status}else{$null};prompt_sentinel_match=if($childResult -and $childResult.capture){$childResult.capture.prompt_match_status}else{$null};response_lifecycle=if($childResult -and $childResult.capture){[bool]$childResult.capture.response_closed}else{$false};status=$status;classification=$classification;copy_result=if($copyExit -ge 8){'FAILURE'}elseif($null -eq $copyExit){'NOT_STARTED'}else{'SUCCESS'};cleanup=@{clone_root_present_before_cleanup=$cloneBefore;clone_root_present_after_cleanup=(-not[IO.Directory]::Exists($session));temporary_root_removed=$cloneRemoved;original_instance_survived=((@(Get-Process -Id $protected -ErrorAction SilentlyContinue).Count)-eq $protected.Count);child_exit_code=$childExit};auth_material_inspected=$false;auth_material_committed=$false;auth_material_hashed=$false};WriteSafe (Join-Path $EvidenceDirectory ('profile-clone-result-'+$runId+'.json')) $result}
if($status -ne 'PASS'){exit 1}
