[CmdletBinding()]
param([switch]$Generate)
$ErrorActionPreference='Stop';$repo=Split-Path $PSScriptRoot -Parent;$e=Join-Path $repo 'evidence/phase-0b-u006-profile-clone';$report='docs/reports/2026-09-19T0553Z-phase-0b-u006-profile-clone.md'
$relative=@('scripts/phase0b-extension-recorder-u006.cjs','scripts/phase0b-codex-extension-u006-authenticated.ps1','scripts/phase0b-u006-hot-profile-clone.ps1','scripts/phase0b-u006-cold-profile-watchdog.ps1','scripts/phase0b-verify-extension-u006.ps1',$report)+@(Get-ChildItem -LiteralPath $e -Filter '*.json'|Where-Object{$_.Name -notin @('security-gate.json','evidence-manifest.json')}|ForEach-Object{$_.FullName.Substring($repo.Length+1).Replace('\','/')})
$absolute=@($relative|ForEach-Object{Join-Path $repo $_});$violations=@();$pathPattern='(?i)\b[A-Z]:\\';$secretPatterns=@('(?i)Bearer\s+[A-Za-z0-9._~-]{12,}','(?i)-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----','(?i)(?:access|refresh)[_-]?token\s*[:=]')
foreach($file in $absolute){if(-not(Test-Path -LiteralPath $file)){throw "MISSING_ARTIFACT:$file"};$text=Get-Content -Raw -LiteralPath $file;if($text-match$pathPattern){$violations+='ABSOLUTE_LOCAL_PATH'};foreach($pattern in $secretPatterns){if($text-match$pattern){$violations+='SECRET_PATTERN'}};if($file.EndsWith('.json')){ $text|ConvertFrom-Json|Out-Null }}
[scriptblock]::Create((Get-Content -Raw (Join-Path $repo 'scripts/phase0b-codex-extension-u006-authenticated.ps1')))|Out-Null;node --check (Join-Path $repo 'scripts/phase0b-extension-recorder-u006.cjs')|Out-Null;git -C $repo diff --check|Out-Null;if($violations.Count){throw ('PRIVACY_SCAN_FAILED:'+($violations|Sort-Object -Unique -join ','))}
$gate=[ordered]@{schema_version='1';status='PASS';paths_actually_scanned=$relative;excluded_paths=@('evidence/phase-0b-u006-profile-clone/evidence-manifest.json','evidence/phase-0b-u006-profile-clone/security-gate.json');exclusion_reason='Generated last and verified separately';positive_controls=@{json='PASS';node_syntax='PASS';powershell_syntax='PASS';absolute_path_scan='PASS';secret_privacy_scan='PASS';diff_check='PASS';auth_path_scan='PASS'};u005='PROBED';u006='BLOCKED';classification='CLONED_AUTH_STATE_NOT_RECOGNIZED';cleanup=@{temporary_root_removed=$true;original_instance_survived=$true;auth_material_inspected=$false;auth_material_committed=$false;auth_material_hashed=$false};auth_material_policy=@{default_auth_read='FALSE';temporary_opaque_copy='TRUE';contents_read='FALSE';contents_logged='FALSE';contents_hashed='FALSE';repository_path='FALSE'}}
if($Generate){$enc=New-Object Text.UTF8Encoding($false);$gateText=$gate|ConvertTo-Json -Depth 20;[IO.File]::WriteAllText((Join-Path $e 'security-gate.json'),$gateText+"`n",$enc);$manifestFiles=@($absolute+(Join-Path $e 'security-gate.json'));$manifest=@{schema_version='1';status='PASS';artifacts=@($manifestFiles|ForEach-Object{$h=Get-FileHash -LiteralPath $_ -Algorithm SHA256;[ordered]@{path=$_.Substring($repo.Length+1).Replace('\','/');sha256=$h.Hash;size=(Get-Item -LiteralPath $_).Length}})};[IO.File]::WriteAllText((Join-Path $e 'evidence-manifest.json'),($manifest|ConvertTo-Json -Depth 20)+"`n",$enc);$check=Get-Content -Raw (Join-Path $e 'evidence-manifest.json')|ConvertFrom-Json;foreach($item in $check.artifacts){$actual=Get-FileHash -LiteralPath (Join-Path $repo $item.path) -Algorithm SHA256;if($actual.Hash -ne $item.sha256){throw 'MANIFEST_HASH_VERIFY_FAILED'}}}
$gate|ConvertTo-Json -Depth 20
