[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$SessionRoot,[string]$EvidenceDirectory,[int]$TimeoutMinutes=40)
$ErrorActionPreference='Stop';$enc=New-Object Text.UTF8Encoding($false);$repo=Split-Path $PSScriptRoot -Parent
if(-not$EvidenceDirectory){$EvidenceDirectory=Join-Path $repo 'evidence/phase-0b-u006-profile-clone'}
$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$session=[IO.Path]::GetFullPath($SessionRoot);if(-not$session.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase)-or(Split-Path $session -Leaf)-notmatch '^dual-pool-u006-cold-[a-f0-9]{32}$'){throw 'UNSAFE_SESSION_ROOT'}
$started=[DateTime]::UtcNow;$runId=$started.ToString('yyyyMMddTHHmmssfffZ');$deadline=$started.AddMinutes($TimeoutMinutes);$clone=Join-Path $session 'user-data';$child=Join-Path $temp ('dual-pool-extension-probe-'+[Guid]::NewGuid().ToString('N'));$status='BLOCKED';$classification='RUNNING';$copyExit=$null;$childExit=$null;$childResult=$null;$originalRelaunched=$false
function WriteSafe([string]$p,$v){$text=$v|ConvertTo-Json -Depth 30;if($text-match'(?i)\b[A-Z]:\\'){throw 'UNSAFE_EVIDENCE'};[IO.File]::WriteAllText($p,$text+"`n",$enc)}
function State([string]$name){Write-Host ('[STATE] '+$name);WriteSafe (Join-Path $session 'state.json') @{run_id=$runId;state=$name}}
function CopyOpaque([string]$source,[string]$destination){New-Item -ItemType Directory -Path $destination -Force|Out-Null;$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName='robocopy.exe';$psi.Arguments='"'+$source+'" "'+$destination+'" /E /COPY:DAT /DCOPY:DAT /XJ /R:0 /W:0 /NFL /NDL /NP /NJH /NJS';$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$p=[Diagnostics.Process]::Start($psi);$null=$p.StandardOutput.ReadToEnd();$null=$p.StandardError.ReadToEnd();$p.WaitForExit();return $p.ExitCode}
try {
  New-Item -ItemType Directory -Path $session,(Join-Path $session 'state'),$EvidenceDirectory -Force|Out-Null;State 'READY';Write-Host 'Dual Pool U-006 Cold Clone Watchdog';Write-Host 'Save work and close all original Antigravity windows.';Write-Host 'The watchdog waits for a quiet source profile and never force-closes the IDE.';State 'WAIT_ORIGINAL_CLOSE';while(@(Get-Process -Name 'Antigravity IDE' -ErrorAction SilentlyContinue).Count -gt 0 -and[DateTime]::UtcNow-lt$deadline){Start-Sleep -Seconds 2};if(@(Get-Process -Name 'Antigravity IDE' -ErrorAction SilentlyContinue).Count -gt 0){$classification='SOURCE_PROFILE_NOT_QUIESCENT';throw 'SOURCE_PROFILE_NOT_QUIESCENT'};State 'SOURCE_PROFILE_QUIESCENT';$source=Join-Path $env:APPDATA 'Antigravity IDE';if(-not[IO.Directory]::Exists($source)){throw 'SOURCE_PROFILE_ABSENT'};State 'COLD_PROFILE_CLONE';$copyExit=CopyOpaque $source $clone;if($copyExit -ge 8){$classification='COLD_PROFILE_CLONE_FAILED';throw 'COLD_PROFILE_CLONE_FAILED'}
  State 'WAIT_ORIGINAL_RELAUNCH';Write-Host 'The owner must now reopen the original Antigravity IDE manually.';for($i=0;$i -lt 300 -and @(@(Get-Process -Name 'Antigravity IDE' -ErrorAction SilentlyContinue)).Count -eq 0;$i++){Start-Sleep -Seconds 1};$originalRelaunched=(@(Get-Process -Name 'Antigravity IDE' -ErrorAction SilentlyContinue).Count -gt 0);if(-not$originalRelaunched){throw 'ORIGINAL_NOT_RELAUNCHED_BY_OWNER'};State 'ORIGINAL_RUNNING';$childArgs=@('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $PSScriptRoot 'phase0b-codex-extension-u006-authenticated.ps1'),'-SessionRoot',$child,'-UserDataDirSource',$clone,'-EvidenceDirectory',$EvidenceDirectory,'-TimeoutMinutes',$TimeoutMinutes);State 'START_RECORDER';$cp=Start-Process powershell.exe -WindowStyle Hidden -PassThru -ArgumentList $childArgs;State 'LAUNCH_CLONED_PROBE';$cp.WaitForExit();$childExit=$cp.ExitCode;$childResult=@(Get-ChildItem -LiteralPath $EvidenceDirectory -Filter 'u006-*.json'|Sort-Object LastWriteTime|Select-Object -Last 1|ForEach-Object{Get-Content -Raw $_.FullName|ConvertFrom-Json})|Select-Object -First 1;if($childExit -eq 0){$status='PASS';$classification='PASS'}else{$classification=if($childResult){$childResult.classification}else{'CLONED_AUTH_STATE_NOT_RECOGNIZED'}}
}catch{$classification=if($classification -eq 'RUNNING'){$_.Exception.Message}else{$classification}}
finally{$cloneBefore=[IO.Directory]::Exists($clone);$rootBefore=[IO.Directory]::Exists($session);$removed=$false;if([IO.Directory]::Exists($session)){try{Get-ChildItem -LiteralPath $session -Recurse -Force -ErrorAction SilentlyContinue|ForEach-Object{try{$_.Attributes='Normal'}catch{}};[IO.Directory]::Delete($session,$true);$removed=(-not[IO.Directory]::Exists($session))}catch{}};$result=[ordered]@{schema_version='1';test_id='P0B-CX-PROFILE-CLONE-001';run_id=$runId;clone_mode='COLD';source_profile_discovery='DEFAULT_PRODUCT_USER_DATA';source_profile_present=$true;auth_profile_copy_mode='OPAQUE_FULL_PROFILE';authentication_clone_recognized=if($childResult){[bool]$childResult.authentication_context_present}else{$false};astra_visible=if($childResult){if($childResult.classification -eq 'AUTHENTICATED_ASTRA_NOT_VISIBLE'){$false}else{$null}}else{$null};astra_selected=if($childResult){[bool]$childResult.astra_selected}else{$false};wire_route=if($childResult -and $childResult.capture){$childResult.capture.route}else{$null};wire_model=if($childResult -and $childResult.capture){$childResult.capture.model}else{$null};custom_provider_retained=if($childResult -and $childResult.capture){$true}else{$false};auth_sentinel_match=if($childResult -and $childResult.capture){$childResult.capture.auth_match_status}else{$null};prompt_sentinel_match=if($childResult -and $childResult.capture){$childResult.capture.prompt_match_status}else{$null};response_lifecycle=if($childResult -and $childResult.capture){[bool]$childResult.capture.response_closed}else{$false};status=$status;classification=$classification;copy_result=if($copyExit -ge 8){'FAILURE'}elseif($null -eq $copyExit){'NOT_STARTED'}else{'SUCCESS'};original_relaunched=$originalRelaunched;cleanup=@{clone_root_present_before_cleanup=$cloneBefore;clone_root_present_after_cleanup=(-not[IO.Directory]::Exists($clone));temporary_root_removed=$removed;original_instance_survived=$originalRelaunched;child_exit_code=$childExit};auth_material_inspected=$false;auth_material_committed=$false;auth_material_hashed=$false};WriteSafe (Join-Path $EvidenceDirectory ('profile-clone-result-'+$runId+'.json')) $result;Write-Host ('[DONE] '+$classification)}
if($status -ne 'PASS'){exit 1}
