[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$SessionRoot,[string]$EvidenceDirectory,[int]$TimeoutMinutes=45)
$ErrorActionPreference='Stop';$enc=New-Object Text.UTF8Encoding($false);$repo=Split-Path $PSScriptRoot -Parent;if(-not$EvidenceDirectory){$EvidenceDirectory=Join-Path $repo 'evidence/phase-0b-u006-primary-profile'};$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$session=[IO.Path]::GetFullPath($SessionRoot);if(-not$session.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase)-or(Split-Path $session -Leaf)-notmatch '^dual-pool-u006-primary-[a-f0-9]{32}$'){throw 'UNSAFE_SESSION_ROOT'}
$runId=([DateTime]::UtcNow).ToString('yyyyMMddTHHmmssfffZ');$stateDir=Join-Path $session 'state';$backupDir=Join-Path $session 'backup';$recDir=Join-Path $session 'recorder';$config=Join-Path $env:USERPROFILE '.codex/config.toml';$settings=Join-Path $env:APPDATA 'Antigravity IDE/User/settings.json';$ideExe=Join-Path $env:LOCALAPPDATA 'Programs/Antigravity IDE/Antigravity IDE.exe';$stage='PRECHECK';$classification='RUNNING';$rec=$null;$port=$null;$secret='SECRET_SENTINEL_'+[Guid]::NewGuid().ToString('N');$prompt='ASTRA_PROMPT_SENTINEL_'+[Guid]::NewGuid().ToString('N');$configPresent=$false;$backupCreated=$false;$probeActive=$false;$restorePass=$false;$normalRelaunch=$false;$target=$false;$auth=$false;$astra=$false;$beforeHash='ABSENT';$afterHash='ABSENT';$settingsHash='ABSENT';$extensionHash='ABSENT';$ext=$null;$capture=$null
function WriteSafe([string]$p,$v){$text=$v|ConvertTo-Json -Depth 30;if($text.Contains($secret)-or$text.Contains($prompt)-or$text-match'(?i)\b[A-Z]:\\'){throw 'UNSAFE_EVIDENCE'};[IO.File]::WriteAllText($p,$text+"`n",$enc)}
function State([string]$name,[string[]]$allowed=@()){Set-Variable -Scope Script -Name stage -Value $name;WriteSafe (Join-Path $stateDir 'status.json') @{run_id=$runId;stage=$name;allowed_controls=$allowed};Write-Host ('[STATE] '+$name)}
function HashFile([string]$p){if(Test-Path $p -PathType Leaf){return(Get-FileHash $p -Algorithm SHA256).Hash};return 'ABSENT'}
function Pids(){@(Get-Process -Name 'Antigravity IDE' -ErrorAction SilentlyContinue|Select-Object -ExpandProperty Id)}
function WaitGone([int]$seconds){$until=[DateTime]::UtcNow.AddSeconds($seconds);while([DateTime]::UtcNow-lt$until){if((Pids).Count-eq 0){return $true};Start-Sleep 1};return $false}
function WaitControl([string[]]$names){State $stage $names;$until=[DateTime]::UtcNow.AddMinutes(20);while([DateTime]::UtcNow-lt$until){foreach($n in $names){if(Test-Path (Join-Path (Join-Path $stateDir 'control') $n)){return $n}};Start-Sleep -Milliseconds 500};throw 'USER_ASSISTED_PROBE_TIMEOUT'}
function AtomicReplace([string]$source,[string]$target){$tmpBackup=$source+'.replace-backup';if(Test-Path $target){[IO.File]::Replace($source,$target,$tmpBackup,$true);if(Test-Path $tmpBackup){Remove-Item $tmpBackup -Force}}else{Move-Item $source $target -Force}}
function RestoreConfig(){if(-not$probeActive){return};if($backupCreated){$restore=Join-Path (Split-Path $config) ('.dualpool-restore-'+[Guid]::NewGuid().ToString('N')+'.tmp');Copy-Item (Join-Path $backupDir 'config.toml') $restore -Force;AtomicReplace $restore $config}else{if(Test-Path $config){Remove-Item $config -Force}};$script:afterHash=HashFile $config;$script:restorePass=($afterHash-eq$beforeHash)}
function StartRecorder(){New-Item $recDir -ItemType Directory -Force|Out-Null;$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=(Get-Command node.exe).Source;$si.Arguments='"'+(Join-Path $PSScriptRoot 'phase0b-extension-recorder-primary.cjs')+'"';$si.UseShellExecute=$false;$si.CreateNoWindow=$true;foreach($kv in @{P0B_PRIMARY_ROOT=$recDir;P0B_PRIMARY_SECRET=$secret;P0B_PRIMARY_PROMPT=$prompt}.GetEnumerator()){$si.EnvironmentVariables[$kv.Key]=$kv.Value};$script:rec=[Diagnostics.Process]::Start($si);$ready=Join-Path $recDir 'ready.json';$until=[DateTime]::UtcNow.AddSeconds(15);while(-not(Test-Path $ready)-and[DateTime]::UtcNow-lt$until){Start-Sleep -Milliseconds 100};if(-not(Test-Path $ready)){throw 'RECORDER_NOT_READY'};$r=Get-Content -Raw $ready|ConvertFrom-Json;$script:port=[int]$r.port;$l=@(Get-NetTCPConnection -State Listen -LocalPort $port);if($l.Count-ne 1-or$l[0].LocalAddress-ne'127.0.0.1'-or$l[0].OwningProcess-ne$rec.Id){throw 'RECORDER_OWNERSHIP_FAILED'}}
function ValidateToml([string]$p){$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=(Get-Command python.exe).Source;$si.Arguments='-c "import sys,tomllib; tomllib.load(open(sys.argv[1], ''rb''))" "'+$p+'"';$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$q=[Diagnostics.Process]::Start($si);$q.WaitForExit();if($q.ExitCode-ne 0){throw 'CONFIG_PROBE_WRITE_FAILED'}}
try{
 New-Item $session,$stateDir,$backupDir,$recDir,(Join-Path $stateDir 'control'),$EvidenceDirectory -ItemType Directory -Force|Out-Null;State 'PRECHECK';$configPresent=Test-Path $config -PathType Leaf;$beforeHash=HashFile $config;$settingsHash=HashFile $settings;$extRoot=Join-Path $env:USERPROFILE '.antigravity-ide/extensions';$ext=@(Get-ChildItem $extRoot -Directory|Where-Object{$_.Name-like'openai.chatgpt-*'});if($ext.Count-ne 1){throw 'EXTENSION_DISCOVERY_FAILED'};$extensionHash=HashFile (Join-Path $ext[0].FullName 'package.json');if((Pids).Count-eq 0){throw 'ORIGINAL_IDE_NOT_RUNNING'};State 'WATCHDOG_READY';WriteSafe (Join-Path $stateDir 'heartbeat.json') @{status='WATCHDOG_READY';watchdog_pid=$PID;owned=$true}
 if($configPresent){Copy-Item $config (Join-Path $backupDir 'config.toml') -Force;$backupCreated=$true;$sibling=Join-Path (Split-Path $config) ('.config.toml.dualpool-u006-backup-'+$runId);Copy-Item $config $sibling -Force};WriteSafe (Join-Path $stateDir 'recovery-marker.json') @{restore_required=$true;original_state=if($configPresent){'PRESENT'}else{'ABSENT'};original_sha256=$beforeHash};State 'BACKUP_COMPLETE';Write-Host 'Save work and close all Antigravity windows normally.';State 'WAIT_PRIMARY_CLOSE';if(-not(WaitGone 900)){throw 'PRIMARY_CLOSE_TIMEOUT'};State 'PRIMARY_CLOSED';StartRecorder;State 'RECORDER_READY'
 $toml="model_provider = `"dualpool_probe`"`n`n[model_providers.dualpool_probe]`nname = `"Dual Pool Phase 0B U-006`"`nbase_url = `"http://127.0.0.1:$port/v1`"`nwire_api = `"responses`"`nenv_key = `"DUALPOOL_CODEX_KEY`"`n";$stageFile=Join-Path (Split-Path $config) ('.dualpool-probe-'+$runId+'.tmp');[IO.File]::WriteAllText($stageFile,$toml,$enc);ValidateToml $stageFile;AtomicReplace $stageFile $config;$probeActive=$true;State 'PROBE_CONFIG_ACTIVE';$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$ideExe;$si.Arguments='--new-window';$si.WorkingDirectory=Split-Path $ideExe;$si.UseShellExecute=$false;$si.EnvironmentVariables['DUALPOOL_CODEX_KEY']=$secret;$null=[Diagnostics.Process]::Start($si);$until=[DateTime]::UtcNow.AddSeconds(90);while((Pids).Count-eq 0-and[DateTime]::UtcNow-lt$until){Start-Sleep 1};if((Pids).Count-eq 0){throw 'NORMAL_RELAUNCH_FAILED'};$normalRelaunch=$true;State 'PRIMARY_RELAUNCHED_FOR_PROBE'
 $choice=WaitControl @('auth-ok','auth-lost');if($choice-eq'auth-lost'){$classification='PRIMARY_AUTH_NOT_RECOGNIZED_AFTER_RELAUNCH';throw $classification};$auth=$true;$choice=WaitControl @('astra-selected','astra-not-visible');if($choice-eq'astra-not-visible'){$classification='AUTHENTICATED_ASTRA_NOT_VISIBLE';throw $classification};$astra=$true;[IO.File]::WriteAllText((Join-Path $stateDir 'astra-prompt.txt'),"Phase 0B primary Astra synthetic transport check. Reply briefly.`r`n$prompt`r`n",$enc);Write-Host 'Send the exact synthetic prompt once in Codex.';$null=WaitControl @('astra-sent');$capturePath=Join-Path $recDir 'capture-u006.json';$until=[DateTime]::UtcNow.AddMinutes(10);while(-not(Test-Path $capturePath)-and[DateTime]::UtcNow-lt$until){Start-Sleep -Milliseconds 300};if(-not(Test-Path $capturePath)){throw 'TARGET_REQUEST_TIMEOUT'};$capture=Get-Content -Raw $capturePath|ConvertFrom-Json;$target=$true;if($capture.model_exact_astra-ne$true){$classification='WIRE_MODEL_NOT_GPT_6_ASTRA';throw $classification};if($capture.auth_match_status-ne'PASS'){$classification='SYNTHETIC_AUTH_MISMATCH';throw $classification};if($capture.prompt_match_status-ne'PASS'){$classification='PROMPT_SENTINEL_NOT_FOUND';throw $classification};if(-not$capture.response_closed){$classification='RESPONSE_LIFECYCLE_FAILED';throw $classification};$classification='PASS'
}catch{$classification=if($classification-eq'RUNNING'){$_.Exception.Message}else{$classification}}
finally{State 'WAIT_PROBE_CLOSE' @('probe-closed');if($probeActive -and(WaitGone 900)){try{RestoreConfig}catch{$restorePass=$false}};if($restorePass){$afterHash=HashFile $config;State 'RELAUNCH_NORMAL';$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$ideExe;$si.Arguments='--new-window';$si.WorkingDirectory=Split-Path $ideExe;$si.UseShellExecute=$false;$null=[Diagnostics.Process]::Start($si);$until=[DateTime]::UtcNow.AddSeconds(90);while((Pids).Count -eq 0-and[DateTime]::UtcNow-lt$until){Start-Sleep 1};$normalRelaunch=((Pids).Count -gt 0);State 'VERIFY_RESTORE'}else{State 'RESTORE_PENDING'};if($rec -and -not $rec.HasExited){try{$rec.Kill();$rec.WaitForExit(5000)|Out-Null}catch{}};$listenerGone=($null -eq $port -or (@(Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue).Count -eq 0));$settingsAfter=HashFile $settings;$extensionAfter=if($ext){HashFile (Join-Path $ext[0].FullName 'package.json')}else{'ABSENT'};$result=[ordered]@{schema_version='1';test_id='P0B-CX-PRIMARY-MODEL-001';run_id=$runId;primary_profile_used=$true;authentication_confirmed=$auth;astra_visible=$astra;astra_selected=$astra;target_request_captured=$target;target_model=if($capture){$capture.model}else{$null};wire_route=if($capture){$capture.route}else{$null};custom_provider_retained=if($capture){$true}else{$false};synthetic_auth=if($capture){$capture.auth_match_status}else{$null};prompt_sentinel=if($capture){$capture.prompt_match_status}else{$null};response_lifecycle=if($capture){$capture.response_closed}else{$false};background_request_count=if($capture){$capture.background_request_count}else{$null};status=if($classification -eq'PASS'-and$restorePass){'PASS'}else{'BLOCKED'};classification=$classification;config=@{original_state=if($configPresent){'PRESENT'}else{'ABSENT'};backup_created=$backupCreated;temporary_mutation=$probeActive;config_before_sha256=$beforeHash;config_after_sha256=$afterHash;byte_for_byte_restore=$restorePass};controls=@{settings_before_sha256=$settingsHash;settings_unchanged=(HashFile $settings -eq$settingsHash);extension_before_sha256=$extensionHash;extension_unchanged=(HashFile (Join-Path $ext[0].FullName 'package.json')-eq$extensionHash);normal_relaunch=$normalRelaunch;listener_absent=$listenerGone};cleanup=@{auth_material_inspected=$false;auth_material_committed=$false;temp_root_removed=$false};failure_classification=$classification};WriteSafe (Join-Path $EvidenceDirectory ('watchdog-result-'+$runId+'.json')) $result;if($restorePass){if($sibling-and(Test-Path $sibling)){Remove-Item $sibling -Force};try{Get-ChildItem $session -Recurse -Force|ForEach-Object{try{$_.Attributes='Normal'}catch{}};[IO.Directory]::Delete($session,$true)}catch{}}}
if($classification-ne'PASS'-or-not$restorePass){exit 1}
